version: '3.8'
server:
  port: 8081

spring:
  application:
    name: user-service
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.8
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.7.8
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  eureka:
    client:
      register-with-eureka: false
      fetch-registry: false
    server:
      wait-time-in-ms-when-sync-empty: 0
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - user-service
      - notification-service
  service-discovery:
    image: docker.io/library/consul:latest
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command: "agent -dev -client=0.0.0.0.0"
  external-config:
    image: springcloud/configserver:latest
    ports:
      - "8888:8888"
    environment:
      SPRING_PROFILES_ACTIVE: native
      SERVER_PORT: 8888
    volumes:
      - ./config-repo:/config-repo
  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CONFIG_SERVER_URI: http://external-config:8888
      SERVICE_DISCOVERY_URI: http://service-discovery:8500
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      DB_HOST: postgres
      DB_PORT: 5432
    depends_on:
      - external-config
      - service-discovery
      - kafka
      - postgres
  notification-service:
    build: ./notification-service
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      CONFIG_SERVER_URI: http://external-config:8888
      SERVICE_DISCOVERY_URI: http://service-discovery:8500
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - external-config
      - service-discovery
      - kafka