spring.application.name=aston_hw
spring.datasource.url=jdbc:postgresql://localhost:5432/aston_hw_db
spring.datasource.username=postgres
spring.datasource.password=postgreY

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
